### PR TITLE
Adding role for collectd sensubility

### PR DESCRIPTION
**Pull request by lnatapov**
1.Adding test for container down health status
2.Adding test for container up health status

### CODE REVIEW

**Review by elfiesmelfie — COMMENTED** [review]
I think this could be grouped with collectd.

I can refactor to make test_collectd into its own role.

**Comment by lnatapov** [comment]
> I think this could be grouped with collectd.
> 
> I can refactor to make test_collectd into its own role.

It makes sense

**Comment by elfiesmelfie** [comment]
I'm working on refactoring the collectd (and other roles) here: https://github.com/infrawatch/functional-tests/pull/53

**Review by csibbitt — APPROVED** [review]
LGTM

**Pull request merged**
